dataset_format: "coco"
dataset_task: "segmentation"
task: scale
scale_factor: 8
image_shape: null # or [H,W]
resize_image_method: "bicubic"
resize_mask_method: "nearest"
show: True
save: False
images_path: "C:\\Users\\a926163\\OneDrive - Eviden\\Escritorio\\Github\\datasets\\coco_densepose\\archive\\coco2014\\images\\train2014"
labels_path: "C:\\Users\\a926163\\OneDrive - Eviden\\Escritorio\\Github\\datasets\\coco_densepose\\archive\\coco2014\\annotations\\densepose_train2014.json"
images_output_path: "C:\\Users\\a926163\\OneDrive - Eviden\\Escritorio\\Github\\datasets\\archive\\coco2017\\test_densepose\\images"
labels_output_path: "C:\\Users\\a926163\\OneDrive - Eviden\\Escritorio\\Github\\datasets\\archive\\coco2017\\test_densepose\\densepose_train2017.json"
