name: documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -e .
          pip install sphinx sphinx_rtd_theme sphinx_markdown_tables recommonmark
      - name: Sphinx build
        run: |
          sphinx-apidoc --output-dir docs resize_dataset/ --separate
          sphinx-build docs docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
