name: PR Content Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check PR description for mandatory content
      run: |
        PR_BODY=$(jq -r .pull_request.body < $GITHUB_EVENT_PATH)
        MANDATORY_SECTIONS=("Summary" "Description" "How to test")
        
        for SECTION in "${MANDATORY_SECTIONS[@]}"; do
          if [[ "$PR_BODY" != *"$SECTION"* ]]; then
            echo "The PR description must contain a '$SECTION' section." >&2
            exit 1
          fi
        done

        echo "PR description contains all mandatory sections."
